### ISSUE TITLE
Robot Pose Telemetry

### ISSUE THREAD

**Issue by Kenneth-Olibrice** [The-Founders-Academy/2024-Centerstage#4]
@aprettygoodprogramer @IanP07  as we discussed during yesterday's meeting, I'd like you two to separately create two new branches off main with your first names on them. The task I am assigning you two is to send the robot's pose data to the driver station using telemtry.addData() and telemetry.update().

This task is more complicated than how we discussed it, and you two will actually need to create a new subsystem to handle it. I have created some instructions and hints that do not give away the solution but will help you two get started:

HINT 1: You will not need to make a command or Opmode to complete this task. All you will need to do is create ONE new subsystem. If you don't know how to create a subsystem, consider reviewing the #[https://docs.ftclib.org/ftclib/command-base/command-system](url) library guide or the [https://javadoc.io/doc/com.arcrobotics/ftclib/latest/index.html](url) official javadocs. We already have some other subsystems written in our code, so you can take a look at those files to get a feel for how to setup a subsystem as well.

HINT 2: the telemetry object is a member of the OpMode class. This means that to use any telemtry.add() or telemetry.update() in another file, you have to pass the OpMode's telemetry object to the file you want to use it in somehow.

 Once you've created the subsystem and successfully passed Teleop.java's telemetry object to it, you'll need a way to update telemetry periodically. The SubsystemBase superclass already has a function you can override to do this, you will just need to consult the docs to find out which one will work best.

As always if you have any questions, @ me in the programming channel on Slack or reply to this issue on Github.

**Comment by aprettygoodprogramer** [comment]
I am unable to add a branch to the repository, I am getting the error "remote: Write access to repository not granted.". The problem may be you have not added me to the repository, but I am not that experienced with git hub.

**Comment by Kenneth-Olibrice** [comment]
@aprettygoodprogramer I just added the team to the project. You should both have access to branching and contributing now.

**Comment by aprettygoodprogramer** [comment]
I just wrote part of the subclass for telemetry, please tell me if i did  something  wrong or forgot to do something.

edit: I forgot to mention since there are no odometry function I had to write the code and then comment it out, I will need to change it when the odometry functions are written.

**Comment by Kenneth-Olibrice** [comment]
@aprettygoodprogramer This is a good start! I was actually entirely wrong about how we should approach this, and you can get an idea why by the fact that you can't access the robot's position inside of the subsystem you made.

The quickest way to accomplish our goal is actually a lot easier and simply involves passing our opmode's telemetry object into the drivetrain's constructor and calling telemetry.addData() to the end of the constructor with the data we want to display to the driver station (x, y, and angle for now). Then, we can call telemetry.update() at the end of run() in Teleop.java.

We may want to have an actual telemetry subsystem and commands in the future, but for now, it would be too much work for too little reward to set it up.

**Comment by Kenneth-Olibrice** [comment]
@aprettygoodprogramer Take a look at @IanP07 's code. It is currently commented out, but it is very close to what we will need to do!

For both of you, look at this [https://github.com/The-Founders-Academy/OperationOverlord/commit/bdf4dac3e7ba97e9a2b68617848597f21344abdc](url) commit I made just now. It should help get you guys started on writing telemetry. Keep in mind that we need the robot's x, y, and rotation in degrees sent to the driver station to properly assess whether our code is working.

**Comment by aprettygoodprogramer** [comment]
the link does not work.

**Comment by Kenneth-Olibrice** [comment]
@aprettygoodprogramer this issue has been resolved and we are working on drivetrain testing. Closing issue now.
